### ISSUE TITLE
Not able to take a measurement using new GUI

### ISSUE THREAD

**Issue by javierconcha** [HYPERNETS/hypernets_tools#10]
Hello @corizzi! (All!)

I am trying to take a measurement using the new GUI, but I am getting the error:

`--> [VNIR IRRADIANCE 32 0] x 1
Spectrum #0 added
Error : [Errno 2] No such file or directory: 'DATA/20210129T152920_VNIR_Irr_00032_00000_01.spe`

I am running the GUI from the rugged PC for now.

I attached a screenshot of the error.

What am I missing?

![Screenshot_2021-01-29_16-29-46](https://user-images.githubusercontent.com/3998620/106294278-4553f280-624f-11eb-9cbd-1b9e5ca03beb.png)

**Comment by javierconcha** [comment]
This is my config file, just in case:
`
# Note : parameters should be unique

[general]
keep_pc = on
start_sequence = yes
sequence_file = hypernets/resources/sequences_samples/your_sequence.csv

webcam_sky = credentials@ip_cam_sky
webcam_site = credentials@ip_cam_site


[yoctopuce]
yoctopuce_ip  = 10.42.0.110
yocto_prefix1 = OBSVLFR1-13F76F
yocto_prefix2 = OBSVLFR2-13FA31
yocto_gps = YGNSSMK2-XXXXXX


[GPS] 
# In case of no GPS signal
latitude = 43.699
longitude = 7.309

# Options
[SPA]
elevation = 0.0
time_zone = 0

[network]
credentials = user@server
remote_dir = ~/DATA
[pantilt]
offset_pan = 0
offset_tilt = -30
`

**Comment by javierconcha** [comment]
BTW, I already tried creating the ~/DATA folder. Also, I tried changing the remote_dir to "hypernets/resources/sequences_samples/" but keep getting the same error.

**Comment by saberioon** [comment]
@javierconcha to fix it temporarily you have to create a DATA folder where you download/install your hypernets_tools. 

It will store device's readings there

**Comment by javierconcha** [comment]
Thanks @saberioon. Unfortunately, I already tried this. This is what I have:

> [hypernets@hypernets-cnr1 ~]$ pwd
> /home/hypernets
> [hypernets@hypernets-cnr1 ~]$ ls
> DATA       Downloads               hypernets_tools  Public
> Desktop    hypernets_basic_tests   Music            Templates
> Documents  hypernets_from_scratch  Pictures         Videos

**Comment by saberioon** [comment]
Data folder should be there : 
```
~/hypernets_tools/DATA
```

**Comment by javierconcha** [comment]
That's it! Thanks!

**Comment by javierconcha** [comment]
The question now is: how do I change the folder where the sequences are saved?

**Comment by corizzi** [comment]
Hi @javierconcha, 

Just to confirm : _remote_dir_ is a part of _network_ configuration. It aims to tell where the files are going to be transferred on the server side (i.e. to specify the full ssh path _user@credentials:remote_dir_).

About local folder, I am not sure why you want to change the local data folder. If you need an easier access from your home (~) to the data, you can create a _symbolic link_ like this :

`cd ~`
`ln -s hypernets_tools/DATA my_data_shortcut`

**Comment by javierconcha** [comment]
Hi @corizzi! 
I understand now. I got confused because I did not understand the config file content. 
Thanks for the clarification!
