### ISSUE TITLE
Metadata header missing

### ISSUE THREAD

**Issue by clemgoyens** [HYPERNETS/hypernets_tools#12]
Hi @corizzi,

As discussed yesterday, hereby a issue request to add header to the metadata. According to our mail from 14/12/2020 we agreed about the following headers:
[metada-header]
PI = Clém
site_name = Blankaart
SN_Hypstar = 120241
datetime = {datetime}
protocol = {protocol_file_name}
session = premier test en plein air

Could we also add:

Lat=43.69862
Lon=7.30692
Hypernets_tools_version = 000.125478

Thanks!!!
Clémence

**Comment by corizzi** [comment]
Metadata should work with :
https://github.com/HYPERNETS/hypernets_tools/tree/outdoorTest
