### ISSUE TITLE
Error : YoctoApi error : Device not found (yapi:3769) when open_sequence

### ISSUE THREAD

**Issue by javierconcha** [HYPERNETS/hypernets_tools#14]
Hello everyone,

I could not find an issue similar in this repo and I still do not have access to all the tickets in GLPI. Did anyone else face a similar error?:

We are testing the system inside my office. I am receiving the following error when running a sequence:

`[hypernets@hypernets-cnr1 hypernets_tools]$ python -m hypernets.open_sequence -df hypernets/resources/sequences_samples/sequence_water_1_STD_1024.csv`
`== [Line 1] ============================================================`
`--> Requested Position (azimuth : 90.00 / sun ; zenith : 180.00)`
`Error : YoctoApi error : Device not found (yapi:3769)`

However, the measurements and pictures are saved without problem.

Is this related to the not finding the gps issue?

**Comment by corizzi** [comment]
Hi @javierconcha , 

Yes, it is related to your GPS configuration which is not properly set. 
You need to replace the line : `yocto_gps = YGNSSMK2-XXXXXX`.
By your own ID, accessible on http://10.42.0.110:4444

**Comment by javierconcha** [comment]
Thanks @corizzi!
