### ISSUE TITLE
Installation with voila

### ISSUE THREAD

**Issue by clemgoyens** [HYPERNETS/hypernets_tools#16]
Small bug: in installation file with VOILA
When trying to move the P/T, the correct relay does not open! Solution: change the button to "open the correct PT relay" so that the user can choose the relay connected to the PT?
Maybe already fixed (can't test it anymore cause my instrument is on the field ;))

**Comment by corizzi** [comment]
bf15e343841d31262a402c0ad628e0f5e8c30441
