### ISSUE TITLE
Proper planning to ensure that sync of config_hypernets.ini does not led to system failure

### ISSUE THREAD

**Issue by clemgoyens** [HYPERNETS/hypernets_tools#17]
Proper planning to ensure that sync of config_hypernets.ini between rugged PC and server does not led to system failure (e.g., if credentials are changed accidentally). This option is dangerous but very helpful (already used twice ;)). So I think it is nice to keep it but maybe there should be some fields that need to be write protected?

**Comment by corizzi** [comment]
f37c5f6 
5243e7f
