### ISSUE TITLE
systemctl status

### ISSUE THREAD

**Issue by saberioon** [HYPERNETS/hypernets_tools#18]
Hi @corizzi 

I have enabled the systemctl yesterday, but when I check its status today it shows me, system activated at 5:28 am !!! this is its output. I have setup waking conditions from 9 till 17 every 30 min. 

<pre>
lines 1-16/16 (END)...skipping...
● hypernets-sequence.service - Hypernets Sequence Service
     Loaded: loaded (/etc/systemd/system/hypernets-sequence.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Thu 2021-02-04 05:28:33 CET; 4h 41min ago
    Process: 687 ExecStart=/home/gfz/Downloads/hypernets_tools/run_service.sh (code=exited, status=1/FAILURE)
   Main PID: 687 (code=exited, status=1/FAILURE)

Feb 04 05:28:31 gfz-pc1 run_service.sh[973]: --> [Mode : vis | Action : bla | IT 0 ms] x 1 | total time : 0 ms]
Feb 04 05:28:31 gfz-pc1 run_service.sh[973]: --> [VNIR DARK 32768 65535] x 1
Feb 04 05:28:31 gfz-pc1 run_service.sh[973]: Spectrum #0 added
Feb 04 05:28:31 gfz-pc1 run_service.sh[973]: Saved to DATA/CUR20210204T042542/RADIOMETER/01_004_0000_0_0000_128_00_0000_01_0000.spe.
Feb 04 05:28:31 gfz-pc1 run_service.sh[973]: Last AIT-VNIR is now : 32768
Feb 04 05:28:31 gfz-pc1 run_service.sh[973]: Disabling Cooling...
Feb 04 05:28:31 gfz-pc1 run_service.sh[973]: DONE
Feb 04 05:28:33 gfz-pc1 run_service.sh[687]: Option : Keep PC ON
Feb 04 05:28:33 gfz-pc1 systemd[1]: hypernets-sequence.service: Main process exited, code=exited, status=1/FAILURE
Feb 04 05:28:33 gfz-pc1 systemd[1]: hypernets-sequence.service: Failed with result 'exit-code'.
</pre>

Additionally, it is not pushing sequence to the server automatically! 

Any advice?

**Comment by corizzi** [comment]
Hi @saberioon , 

About the early wake-up, are you sure that no power cut did happen ?
Even a micro-cut can turn the system on.
Which power supply do you use ?

For the data transfer, can you please paste the content of  : 
`journalctl -eu hypernets-hello`
Thanks

**Comment by saberioon** [comment]
I'm not sure about the power outrage. 

here shows successful syncing
```
-- Boot 2cf823e5a3444005a528e7416b7c68ca --
Feb 04 05:24:17 gfz-pc1 systemd[1]: Started Hypernets Sync Config Server and Send Data.
Feb 04 05:24:17 gfz-pc1 hello_server.sh[686]: Sleep 30 sec
Feb 04 05:24:49 gfz-pc1 hello_server.sh[686]: Sync files : gfz@139.143.5.63:~/config_hypernets.ini.gfz
Feb 04 05:24:49 gfz-pc1 hello_server.sh[686]:         <->  config_hypernets.ini
Feb 04 05:24:50 gfz-pc1 hello_server.sh[686]: Files are synchronized.
Feb 04 05:24:54 gfz-pc1 systemd[1]: hypernets-hello.service: Succeeded.
```

but in server look at the hypernets-sequence.log 
```
-- Boot 2cf823e5a3444005a528e7416b7c68ca --
Feb 04 05:24:17 gfz-pc1 systemd[1]: Started Hypernets Sequence Service.
Feb 04 05:24:17 gfz-pc1 run_service.sh[687]: Waiting for yoctopuce...
Feb 04 05:24:19 gfz-pc1 run_service.sh[687]: .
Feb 04 05:24:20 gfz-pc1 run_service.sh[687]: .
Feb 04 05:24:22 gfz-pc1 run_service.sh[687]: .
Feb 04 05:24:23 gfz-pc1 run_service.sh[687]: .
Feb 04 05:24:25 gfz-pc1 run_service.sh[687]: .
Feb 04 05:24:26 gfz-pc1 run_service.sh[687]: .
Feb 04 05:24:28 gfz-pc1 run_service.sh[687]: .
Feb 04 05:24:29 gfz-pc1 run_service.sh[687]: .
Feb 04 05:24:31 gfz-pc1 run_service.sh[687]: .
Feb 04 05:24:32 gfz-pc1 run_service.sh[687]: .
Feb 04 05:24:34 gfz-pc1 run_service.sh[687]: .
Feb 04 05:24:35 gfz-pc1 run_service.sh[687]: .
Feb 04 05:24:37 gfz-pc1 run_service.sh[687]: .
Feb 04 05:24:38 gfz-pc1 run_service.sh[687]: .
Feb 04 05:24:40 gfz-pc1 run_service.sh[687]: .
Feb 04 05:24:41 gfz-pc1 run_service.sh[687]: .
Feb 04 05:24:43 gfz-pc1 run_service.sh[687]: .
Feb 04 05:24:45 gfz-pc1 run_service.sh[687]: .
Feb 04 05:24:47 gfz-pc1 run_service.sh[687]: .
```
and hypernets-hello.log 
```
-- Boot 2cf823e5a3444005a528e7416b7c68ca --
Feb 04 05:24:17 gfz-pc1 systemd[1]: Started Hypernets Sync Config Server and Send Data.
Feb 04 05:24:17 gfz-pc1 hello_server.sh[686]: Sleep 30 sec
```

additionally, the sequence is saved in the local drive, not in the server

**Comment by corizzi** [comment]
By taking a closer look at your first log, I saw : 
`Option : Keep PC ON` which means that the sleep mode is disabled.
You probably want `keep_pc = off` in your _config_hypernets.ini_. This will ensure a cleaner start for your sequences.

For the server log, the script waits for 30 seconds before _syncing logs and data_  to ensure that 3G/4G is available. So, if the yocto-wifi module is a bit long to connect, you only get the _waiting period with dots_. However, you should have the full log of the previous sequence on the server (the system is _near real time_).

**Comment by saberioon** [comment]
Thanks, @corizzi, It fixed now when I set the ```keep_pc = off```
