### ISSUE TITLE
NPL server connection setup

### ISSUE THREAD

**Issue by AgaBialek** [HYPERNETS/hypernets_tools#22]
I followed a set of instructions from #8 How to set up network,  I tried to connect to NPL server and was not able to type the password when prompted and the leaving this empty did not work either.

[hypernets_npl@hypernetsnpl-pc hypernets_tools]$ sudo ./install/08_setup_server_communication.sh
[sudo] password for hypernets_npl: 
Sorry, try again.
[sudo] password for hypernets_npl: 
Sorry, try again.
[sudo] password for hypernets_npl: 
sudo: 3 incorrect password attempts

**Comment by jkuusk** [comment]
Your are supposed to type in the rugged PC user 'hypernets_npl' password so that sudo can elevate the privileges to superuser level.

**Comment by AgaBialek** [comment]
Thanks Joel I will try next Tuesday when I back at NPL.
