### ISSUE TITLE
relays status?

### ISSUE THREAD

**Issue by saberioon** [HYPERNETS/hypernets_tools#23]
Hi @corizzi, 

I have tried this command to check the status of relays, but it is not generating any output.  
`python -m hypernets.scripts.relay_command -g`

Any advice?

**Comment by jkuusk** [comment]
https://github.com/HYPERNETS/hypernets_tools/blob/019f1bec5fb7e08e517fbaaabe53920915f320e6/hypernets/scripts/relay_command.py#L132
In my fork I've changed this line to
`get_state_relay(args.id_relay, True)`

**Comment by corizzi** [comment]
@saberioon 

Thanks for the comment
