### ISSUE TITLE
"-bash: make: command not found" when updating libhypstar

### ISSUE THREAD

**Issue by javierconcha** [HYPERNETS/hypernets_tools#25]
When trying to follow the following steps:
"Libhypstar driver is now bundled with installation, but needs to be activated and installed:

cd hypernets_tools
git submodule init
git submodule update
cd hypernets/scripts/libhypstar
make lib
sudo make install"

I am getting the following error:

[hypernets@hypernets-cnr1 libhypstar]$ make lib
-bash: make: command not found

Apparently there is no make to be found in the machine:

[hypernets@hypernets-cnr1 libhypstar]$ which make
which: no make in (/home/hypernets/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)

**Comment by jkuusk** [comment]
pacman -S make

**Comment by javierconcha** [comment]
sudo pacman -S make
worked

**Comment by javierconcha** [comment]
I encountered this issue when installing libhypstar in the second rugged-PC:

```
[hypernets@hypernets-cnr2 libhypstar]$ make lib
----- INFO: Building file src/hypstar.cpp
g++ -rdynamic -fPIC -O0 -g -Wall -Werror -Iinc -Iinc/serial -Iinc/utils -c src/hypstar.cpp -o build/hypstar.o
make: g++: No such file or directory
make: *** [makefile:52: build/hypstar.o] Error 127
```
and I solved it with:

`[hypernets@hypernets-cnr2 libhypstar]$ sudo pacman -Syu base-devel linux-headers`

**Comment by corizzi** [comment]
Hi @javierconcha, 

Thanks for reporting.

https://github.com/HYPERNETS/hypernets_tools/commit/c732b493e0548ea34fb1e83624a434cc3c6ccb14
with installation update already solved this on the main branch.
