### ISSUE TITLE
Cannot connect to the yoctopuse remotely: init error:Unable to connect to server (ytcp:489)

### ISSUE THREAD

**Issue by javierconcha** [HYPERNETS/hypernets_tools#28]
I am working remotely and after a while of being able to open the gui, now I am getting this error:
```
[hypernets@hypernets-cnr1 hypernets_tools]$ python -m hypernets.gui
init error:Unable to connect to server (ytcp:489)
```

Also, is there any way to reset or reboot the yoctopuse remotely?

**Comment by javierconcha** [comment]
I got the same error after rebooting remotely.

**Comment by jkuusk** [comment]
Is the virtualhub service running?
systemctl status yvirtualhub.service

**Comment by javierconcha** [comment]
I got this:

```
[hypernets@hypernets-cnr1 hypernets_tools]$ systemctl status yvirtualhub.service
● yvirtualhub.service - Yoctopuce VirtualHub
     Loaded: loaded (/etc/systemd/system/yvirtualhub.service; enabled; vendor preset: disabled)
     Active: active (running) since Tue 2021-02-23 11:51:33 CET; 4h 36min ago
   Main PID: 341 (VirtualHub)
      Tasks: 4 (limit: 4573)
     Memory: 6.0M
     CGroup: /system.slice/yvirtualhub.service
             └─341 /usr/sbin/VirtualHub -c /etc/vhub.byn

feb 23 11:51:33 hypernets-cnr1 systemd[1]: Started Yoctopuce VirtualHub.
feb 23 11:51:33 hypernets-cnr1 VirtualHub[341]: Cannot register service: RPC: Unable to receive; errno = Connection refused
```

**Comment by jkuusk** [comment]
That looks good. I've seen the 489 error only once and it was fixed after reboot (the Yoctopuce rebooted itself and hence also the rugged PC shortly after that error)

**Comment by javierconcha** [comment]
In my case, the Yoctopuce did not reboot itself after one day. I try to interact with the system, but I get the same error, e.g.,

```
[hypernets@hypernets-cnr1 hypernets_tools]$ python3 -m hypernets.scripts.relay_command -n3 -soff
init error:Unable to connect to server (ytcp:489)
```

**Comment by javierconcha** [comment]
@jkuusk, @corizzi, is there a way to reboot the Yoctopuce remotely?

**Comment by jkuusk** [comment]
If you are unable to connect to the yoctopuce then I think only way of rebooting it is power cycling. Unless you can control the power source remotely I think it is not possible to reboot the yoctopuce.

**Comment by javierconcha** [comment]
@jkuusk, @clemgoyens, all partners, 

From your experience, could this happen on the field? Should we be thinking of a solution, like a remotely controlled switch?

**Comment by jkuusk** [comment]
Yoctopuce itself was supposed to be that switch. In my experience I have not seen such an issue that the yoctopuce is inaccessibe for extended period of time. I've seen occasional errors of not being accessible, I've seen yoctopuce rebooting at random moments, I've seen some commands (switching relays) blocking for nearly 20 minutes. 

Can you connect to the yoctopuce web interface from a browser or that one is inaccessible too? Can you ping the yoctopuce?

**Comment by javierconcha** [comment]
Yes, we can ping and connect to the Yoctopuce by the web interface:
```
[hypernets@hypernets-cnr1 ~]$ ping 127.0.0.1
PING 127.0.0.1 (127.0.0.1) 56(84) bytes of data.
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.070 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.146 ms
64 bytes from 127.0.0.1: icmp_seq=3 ttl=64 time=0.090 ms
```

We have a different error now, when pressing the connection button in the gui:
```
[hypernets@hypernets-cnr1 hypernets_tools]$ python -m hypernets.gui
init error:ytcp:650:tcp(113):No route to host
```

**Comment by jkuusk** [comment]
You are pinging the localhost. Can you ping the yoctopuce IP from the rugged PC (yoctopuce_ip parameter in the configuration file, probably 10.42.0.something)?

**Comment by javierconcha** [comment]
The last time I encounter this error, I could not ping to 10.42.0.X. I have not encountered this error anymore.

**Comment by saberioon** [comment]
When I change the wifi in Yoctowifi to Airplane mode as mentioned in [here ](https://github.com/HYPERNETS/hypernets_tools/tree/beta#instructions---for-usb), I encounter this error when I try to connect in GUI:
`init error:Unable to connect to server (ytcp:489)
`
