### ISSUE TITLE
Wakeup Conditions configuration: Which interval should we set?

### ISSUE THREAD

**Issue by javierconcha** [HYPERNETS/hypernets_tools#30]
@clemgoyens, All,
For these instructions:
```
Wakeup Conditions :
Please refer to the Yoctopuce User Manual to set up Wakeup conditions for the system :
http://www.yoctopuce.com/EN/products/yoctohub-wireless/doc/YHUBWLN1.usermanual.html#CHAP9SEC1
```
I am confused about what we should set here. Is the daily waking up of the Yoctopuce? Or is the Waking up every 15 min for taking the measurement?

Thanks.

**Comment by jkuusk** [comment]
This is the wakeup everty 15 min (or whatever sequence interval you are using) necessary if you select keep_pc = off in the configuration file.

**Comment by javierconcha** [comment]
Got it! Thanks!

**Comment by javierconcha** [comment]
@clemgoyens, just to make sure, this how we control the acquisition interval, every 15 min for the water unit?  

Also, from what time to what time? 9AM local time to 4PM local time?

**Comment by clemgoyens** [comment]
Hi Javier, 
Two things to keep in mind for Blankaart versus AAOT (called VEIT in hypernets processor ;))
1. Platform shadow and shape at Blankaart determines part of my sequence scheduler (its a long wall and HYPSTAR can only measure at one side of the wall)
2. I have no power restrictions at Blankaart

Knowing this:
1. I have currently measurements every 15 min (mainly cause I have some platform disturbance , i.e., water tube) within my FOV and they will appear at regular intervals according to the solar azimuth angle - hence to make sure I have at least 2 measurements per hour I added extra measurements). But Etang de berre measures every 30 min (it is enough to have 2 good measurements per hour and they have power restrictions - solar panels). 
1. I have 8AM till 5PM local time (again, according to my wall orientation and the solar azimuth some of the data will not be usable, instrument sees platefome) but I have no power restriction.

So for VEIT I would suggest you to check when you have usable data according to the instrument set-up and, according to power restrictions, check whether 15 or 30 min interval is feasible.

Hope this helps!

**Comment by javierconcha** [comment]
We are using every 15 min for our deployment outside our building at the end. We are gonna test it on the VEIT in a couple of weeks and decide what interval to use.
