### ISSUE TITLE
Configuration file: parameter "keep_pc", "start_sequence",  and "bypass_yocto" meaning

### ISSUE THREAD

**Issue by javierconcha** [HYPERNETS/hypernets_tools#31]
@corizzi, All,

Sorry if I miss this information from another source, but I want to make sure I understand them correctly. What are the meanings or functionality of these parameters of the config file? What the best setting for the water unit on the field (@clemgoyens)?

```
[general]
keep_pc = on
start_sequence = yes
bypass_yocto = no
```
From #18, the keep_pc should be off, right?

PS: maybe, it could be useful to have some notes explaining the configuration file parameters. I could not find any.

**Comment by javierconcha** [comment]
From a conversation with @corizzi:

*) "keep_pc" determines if pc remains ON or OFF at the end of the sequence.
*) "start_sequence" will start or not a sequence at boot time of the pc.
*) And "bypass_yocto" aims to avoid triggering relays of the yocto card.

**Comment by jkuusk** [comment]
bypass_yocto is for testing the toolchain without the yoctopuce (for Kaspars to work on the radiometer engineering model)

**Comment by corizzi** [comment]
https://github.com/HYPERNETS/hypernets_tools/wiki/config_hypernets.ini-:-definitions

**Comment by javierconcha** [comment]
Thanks @corizzi!
