### ISSUE TITLE
Lot of zeros at the end of image files

### ISSUE THREAD

**Issue by jkuusk** [HYPERNETS/hypernets_tools#34]
The stored jpg images contain lot of zeros in the end of the file (roughly half of the entire file). That doesn't corrupt the images, however, it wastes the disk space and network bandwidth when transferred to the server.

**Comment by corizzi** [comment]
Hi @jkuusk , 
These zeros are in the returned stream of the `download_JPEG_image` of the `hypstar_wrapper`, did you want to post this issue on _libhypstar_ repository ?

**Comment by jkuusk** [comment]
I didn't check where they come from.

**Comment by jkuusk** [comment]
Discussion moved to https://github.com/HYPERNETS/libhypstar/issues/4#issue-823087160
