### ISSUE TITLE
Connecting the cameras

### ISSUE THREAD

**Issue by javierconcha** [HYPERNETS/hypernets_tools#35]
Dear @corizzi,

- I was able to set up the cameras using a Windows machine. So, we have a username and a password for each camera. Looking the "webcamGetImg.sh" script, it seems that the credentials for the cameras needs to be passed as:

credentials=USER:PASS

and therefore, in the config file:

webcam_sky = USER:PASS@ip_cam_sky
webcam_site = USER:PASS@ip_cam_site

Am I right?

- Also, should the IP addresses assigned to the cameras be related to the family of IP addresses assigned to the Yoctopuce? 

- We are assuming that we need to input the rugged-PC Wifi Hotspot credentials when we are close to the Studiel box but using the Windows machine with the software. Right?

**Comment by corizzi** [comment]
Hello @javierconcha ,

Yes the IP addresses should be in the range of the network of the rugged pc : 10.42.0.0/24 _(i.e : 10.42.0.X)_

If you don't have those IPs, you can try : 
`journalctl --follow -u NetworkManager`, then power on the cameras.

Finally, to try if you are able to take a picture with the script :
`./webcamGetImg.sh -i 10.42.0.X -c USER:PASS`

For automation of the process at boot time, I only implemented it in the  _outdoorTest branch_ for now. But I will bring this in the _main branch_ as tests in Berre yields to conclusive results.

**Comment by javierconcha** [comment]
We were able to set the cameras and take pictures from the command line. 

For now, we are using crontab to take a picture with each camera every one minute:
```
* * * * * /home/hypernets/hypernets_tools/webcamGetImg.sh -i 10.42.0.42  -c installer:123456qwer -d /home/hypernets/hypernets_tools/DATA/WEBCAMS/Cam1/ -v
* * * * * /home/hypernets/hypernets_tools/webcamGetImg.sh -i 10.42.0.152 -c installer:123456abcd -d /home/hypernets/hypernets_tools/DATA/WEBCAMS/Cam2/ -v
```

**Comment by javierconcha** [comment]
We encountered a problem while trying to set the cameras. The browser from the Windows machine (IE) was not showing the save setting button in the Wifi settings for some strange reason, and therefore, we could not save the password to the rugged-PC Wifi. The problem was solved by going to a different tab of the setting where the button was visible, and then returning to the Wifi settings, and "magically" the button showed up.

**Comment by corizzi** [comment]
Yes, I got similar issue. I think it was a display error, I solved it by zoom out in the same webpage.

**Comment by javierconcha** [comment]
After the addition of the -p option described in #39, we are running the webcams as: 
[hypernets@hypernets-cnr1 hypernets_tools]$ crontab -l
* * * * * /home/hypernets/hypernets_tools/webcamGetImg.sh -i 10.42.0.42  -c installer:password -d /home/hypernets/hypernets_tools/DATA/WEBCAMS/Cam1/ -v -p VEIT_Cam1  
* * * * * /home/hypernets/hypernets_tools/webcamGetImg.sh -i 10.42.0.152 -c installer:password -d /home/hypernets/hypernets_tools/DATA/WEBCAMS/Cam2/ -v -p VEIT_Cam2

**Comment by corizzi** [comment]
Hi @javierconcha , 

For now, it is only for VEIT as I was waiting for feedback

**Comment by corizzi** [comment]
Now added : 05d0e31ee289d2bc10a22d5705a12f7c429446a7
