### ISSUE TITLE
YoctoApi error : No function of that class (yapi:3811)

### ISSUE THREAD

**Issue by elpiades** [HYPERNETS/hypernets_tools#36]
Hi! Having trouble after running the GUI and trying to make the connection.
This error stack is shown in the console:
<pre>
[iafe1@iafe1-pc hypernets_tools]$ python -m hypernets.gui
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/iafe1/hypernets_tools/hypernets/gui/frame_yoctopuce.py", line 30, in _connection
    self.connection()
  File "/home/iafe1/hypernets_tools/hypernets/gui/frame_yoctopuce.py", line 80, in connection
    states_relay = get_state_relay(-1)
  File "/home/iafe1/hypernets_tools/hypernets/scripts/relay_command.py", line 24, in get_state_relay
    relay_states.append(_alias_get_state(id_relay))
  File "/home/iafe1/hypernets_tools/hypernets/scripts/relay_command.py", line 18, in _alias_get_state
    return tuple((id_relay, relay.get_state()))
  File "/home/iafe1/.local/lib/python3.9/site-packages/yoctopuce/yocto_relay.py", line 137, in get_state
    if self.load(YAPI._yapiContext.GetCacheValidity()) != YAPI.SUCCESS:
  File "/home/iafe1/.local/lib/python3.9/site-packages/yoctopuce/yocto_api.py", line 5220, in load
    self._throw(res, errmsgRef.value)
  File "/home/iafe1/.local/lib/python3.9/site-packages/yoctopuce/yocto_api.py", line 4469, in _throw
    raise YAPI.YAPI_Exception(errType, "YoctoApi error : " + errorMessage)
yoctopuce.yocto_api.YAPI.YAPI_Exception: YoctoApi error : No function of that class (yapi:3811)
</pre>
@corizzi Any idea what could be the reason for that? Thanks in advance!

Pablo

**Comment by corizzi** [comment]
Hi @elpiades, 

How often does this error occur ? Each time you are trying to connect ? Also, is the hypernets-sequence service still running at the same time ?

Thanks

**Comment by elpiades** [comment]
It's happening everytime the 'Connection' button is clicked.
**start-sequence** is set as 'no' in the INI file and the PC has been rebooted many times.

I have to add that this thing started to happen after setting up a remote way to operate the PC. I've installed the **xorg-xauth** package (with some dependencies) using **pacman**.

Now we can forward the GUI through a SSH connection to a notebook, but well... this happens.

I could go back with the last setup procedure but it's really important that we have this feature available; and I don't really think the yocto libraries should be affected by it.

So perhaps you can think of some solution or anything we could try here.

Best regards!!

**Comment by corizzi** [comment]
Hi @elpiades, 

For me, the GUI was not meant to be used through SSH, so I did not try this option and I am not able to tell how this package is related to your error for now.

Do you have the same error with command line option. I mean things such : 
`python -m hypernets.scripts.relay_command -son 3` for example ?
Also, did you try to run voila instead of the GUI ? (see last section of the README.md)
Thanks!

**Comment by jkuusk** [comment]
I've been using the GUI over ssh with X11Forwarding without any problems. If the problem started after installing xorg-xauth with dependencies, I suspect that you may have broken dependencies in the system unless you did full system upgrade when installing xorg-auth (i.e. didn't use -u option of  pacman). Try if running pacman -Syu fixes the error.

**Comment by elpiades** [comment]
Thanks to both of you @corizzi & @jkuusk for your replies.

We've finally found the reason for this exception and it's totally unrelated to the package installation whatsoever.

While tightening the screws that hold the main Yocto board, the 4-pin connector that connects the main board with the relays board (photo attached) broke (the welding got loose actually)

Letting you all know just in case anyone else experiences this error and starts to wonder what happened.

![image](https://user-images.githubusercontent.com/49041665/111205745-5447f780-85a6-11eb-8452-418d6b66f9c5.png)

Thanks again!
Pablo
