### ISSUE TITLE
Reorganising the structure of /DATA

### ISSUE THREAD

**Issue by javierconcha** [HYPERNETS/hypernets_tools#40]
We think that reorganizing the sequences folder by date would help the readability. After a couple of weeks, we have too many folders. 
Moreover, within each sequence folder, all the sequence files have the same name. As an example, having downloaded a few images to understand where the instrument was pointing, all the jpeg are called 01_009_0270_2_0040.

**Comment by corizzi** [comment]
Hi @javierconcha ,

I am not sure if it can help, but you can try this script that copy the images from the radiometer with friendly names instead _(i.e : IR1, SK1, WAT, SK2, IR2, SUN)_  and prefix by sequence name.

https://github.com/HYPERNETS/hypernets_tools/blob/beta/utils/sequences/sequence_utils/gather_images_water_sequence.sh

**Comment by jkuusk** [comment]
DATA/YYYY/MM/DD folder structure has now been implemented
