### ISSUE TITLE
error:ytcp:650:tcp(111):Connection refused

### ISSUE THREAD

**Issue by javierconcha** [HYPERNETS/hypernets_tools#41]
@vitbrando and I are still having this error:
`error:ytcp:650:tcp(111):Connection refused`

Example from the journalctl:

-- Boot 7d19d87261044c9d8ceefefc049dff0c --
mag 31 10:15:39 hypernets-cnr1 systemd[1]: Started Hypernets Sequence Service.
mag 31 10:15:39 hypernets-cnr1 run_service.sh[669]: Waiting for yoctopuce...
mag 31 10:15:41 hypernets-cnr1 run_service.sh[669]: .
mag 31 10:15:42 hypernets-cnr1 run_service.sh[669]: .
mag 31 10:15:44 hypernets-cnr1 run_service.sh[669]: .
mag 31 10:15:45 hypernets-cnr1 run_service.sh[669]: .
mag 31 10:15:47 hypernets-cnr1 run_service.sh[669]: .
mag 31 10:15:48 hypernets-cnr1 run_service.sh[669]: .
mag 31 10:15:48 hypernets-cnr1 run_service.sh[669]: Ok !
mag 31 10:16:09 hypernets-cnr1 run_service.sh[855]: init error:ytcp:650:tcp(111):Connection refused
mag 31 10:16:09 hypernets-cnr1 systemd[1]: hypernets-sequence.service: Main process exited, code=exited, status=1/FAILURE
mag 31 10:16:09 hypernets-cnr1 systemd[1]: hypernets-sequence.service: Failed with result 'exit-code'.
-- Boot abf51ebb98d64b71880ea18054af2db1 --
mag 31 10:45:39 hypernets-cnr1 systemd[1]: Started Hypernets Sequence Service.
mag 31 10:45:39 hypernets-cnr1 run_service.sh[670]: Waiting for yoctopuce...
mag 31 10:45:41 hypernets-cnr1 run_service.sh[670]: .
mag 31 10:45:42 hypernets-cnr1 run_service.sh[670]: .
mag 31 10:45:44 hypernets-cnr1 run_service.sh[670]: .
mag 31 10:45:45 hypernets-cnr1 run_service.sh[670]: .
mag 31 10:45:47 hypernets-cnr1 run_service.sh[670]: .
mag 31 10:45:48 hypernets-cnr1 run_service.sh[670]: .
mag 31 10:45:50 hypernets-cnr1 run_service.sh[670]: .
mag 31 10:45:50 hypernets-cnr1 run_service.sh[670]: Ok !
mag 31 10:46:11 hypernets-cnr1 run_service.sh[860]: init error:ytcp:650:tcp(111):Connection refused
mag 31 10:46:11 hypernets-cnr1 systemd[1]: hypernets-sequence.service: Main process exited, code=exited, status=1/FAILURE
mag 31 10:46:11 hypernets-cnr1 systemd[1]: hypernets-sequence.service: Failed with result 'exit-code'.
-- Boot 57073b994dfc47d9b9374780002438a3 --

**Comment by corizzi** [comment]
Hi @javierconcha , 

Thanks for reporting this. We already have notified the developer team. However we need someone to dump the memory of the module (require physically presence) just after the bug is showing up.

**Comment by corizzi** [comment]
New firmware seems to solve this : aaee85b0131627a3dcea1523f1dceb993fc44e74
(tested for a week now)

**Comment by javierconcha** [comment]
@corizzi ,
The problem has not been solved yet. We (@vitbrando) have to still power cycle it almost everyday. Here we have a log file with the power cycling history:
https://docs.google.com/document/d/1n9u3JS-K7UlRRgo7Qf7Y-do9snoPkm90YJW-VT95GHs/

**Comment by corizzi** [comment]
Hi @javierconcha , did you update the card with the new firmware ?

**Comment by javierconcha** [comment]
To which device are you referring? OBSVLFR1 or OBSVLFR2? And what is the last version number?

**Comment by corizzi** [comment]
Dear @javierconcha,

I was talking about PictorWifi16062021.byn, the new firmware I mentioned here : 

> New firmware seems to solve this : [aaee85b](https://github.com/HYPERNETS/hypernets_tools/commit/aaee85b0131627a3dcea1523f1dceb993fc44e74)
> (tested for a week now)

Please note that PictorWifi (the upper board) is the name of the device, OBSVLFR2 is its serial.

However, I  discovered 5 minutes ago that the web interface is not working anymore with this version on my device, so we should wait a little bit more for a new firmware.
