### ISSUE TITLE
VEIT branch stop rsync with RBINS server with new commit

### ISSUE THREAD

**Issue by javierconcha** [HYPERNETS/hypernets_tools#44]
@corizzi,
I have noticed that every time you do a new commit to the VEIT branch, the rsync with the server stop working. It seems that because our branch in the rugged-PC is behind a commit, the rsync of the DATA does not work. So far, I have been solving it by git stash and then git pull from the rugged-PC. Is this a normal behavior?

**Comment by corizzi** [comment]
Hello @javierconcha, 

This error happened because you have made modification on your local repo. Hence, git raises an error and the script exits before the syncing.

I moved the pull command after syncing so this should be fixed now : 5643cd9b448c4a16429ce558f278a3bacceb6855

**Comment by javierconcha** [comment]
Thanks!

**Comment by corizzi** [comment]
In addition, I added an "auto_update" option for the future version : 9c26b16dee6e578b6004d0d2fd394e3854bf1950
