### ISSUE TITLE
error with launching hypernets.gui 

### ISSUE THREAD

**Issue by saberioon** [HYPERNETS/hypernets_tools#5]
Hi Alex, 

I have encountered this error 
`FileNotFoundError: [Errno 2] No such file or directory: '/hypernets_tools/hypernets/resources/logo.png'
I noticed the logo.png is stored in img, but it calls it from resources. 

I fixed it manually.

**Comment by corizzi** [comment]
Hi Medhi, 
I just fixed it, should work now.
Thanks
