### ISSUE TITLE
Wrong sequence folder name

### ISSUE THREAD

**Issue by javierconcha** [HYPERNETS/hypernets_tools#52]
It seems that the sequence folder name is writing the local time, instead of the UTC time. 
Maybe this line:
https://github.com/HYPERNETS/hypernets_tools/blob/212323e240daa831549b8efb014448ab04192ad6/hypernets/virtual/read_protocol.py#L202
should be changed to:
`now = datetime.utcnow()`

**Comment by corizzi** [comment]
Hi @javierconcha , thanks for the comment but the actual one is:

https://github.com/HYPERNETS/hypernets_tools/blob/1b106f2c957219b1dea8b345d45620f7649a05b6/hypernets/open_sequence.py#L39
