### ISSUE TITLE
time stamp issue 

### ISSUE THREAD

**Issue by saberioon** [HYPERNETS/hypernets_tools#6]
VNIR Irradiance 8 8 1 0 2592 x 1944, 5MP
--> [VNIR IRRADIANCE 8 8] x 1
Spectrum #0 added
Saved to DATA/20210125T142829_VNIR_Irr_00008_00008_01.spe.
Integration Times : VNIR : 8 ms
                  : SWIR : 8 ms
Total Dataset Length : 4131
Spectrum Type Information : ('VIS', 'IRRADIANCE')
**Timestamp : 1970-01-01 02:45:25**
Exposure Time : 8
Temperature : 33.523780822753906
Pixel Count : 2048
mean X : 0
std X : 0
mean Y : 0
std Y : 0
mean Z : 0
std Z : 0

I have checked time and date on rugged PC and it is 
Local time: Mo 2021-01-25 15:25:17 CET
           Universal time: Mo 2021-01-25 14:25:17 UTC
                 RTC time: Mo 2021-01-25 14:25:16
                Time zone: Europe/Berlin (CET, +0100)
System clock synchronized: no
              NTP service: inactive
          RTC in local TZ: no

Any suggestion for fixing it ?!

**Comment by corizzi** [comment]
Hi Medhi, 

This timestamp comes from the spectrum header. I'm not sure if we want to keep "the number of milliseconds since boot" (which is the one you can read now) or the actual utc time in each spectrum. In the last case we should set date and time to the instrument before measurement.
I will add an option anyway. For the rest, your config seems good.
Thanks

**Comment by jkuusk** [comment]
Number of milliseconds since boot makes no sense for the field deployment use case. You should set the radiometer's time after power-on. The millisecond since boot is just a fallback for the radiometer as long as it does not have a correct timestamp.

**Comment by corizzi** [comment]
I agree on that. I patched it.
Thanks

**Comment by stiebrs** [comment]
New driver sets host machine time on the instrument on establishing connection. Only issues should be with internal environment logs which were saved before internal time was set - those will still be milliseconds since boot.
