### ISSUE TITLE
Waiting for yoctopus message !

### ISSUE THREAD

**Issue by saberioon** [HYPERNETS/hypernets_tools#60]
The Yoctopus is turning on the PC but the service is stopped at this stage, Why is this happening? How to fix it ?

-- Boot 3930b5f66e1e46e99ef687a5d2933351 --
Sep 13 10:00:45 gfz-pc systemd[1]: Started Hypernets Sequence Service.
Sep 13 10:00:45 gfz-pc run_service.sh[690]: [INFO]  Waiting for yoctopuce...

**Comment by jkuusk** [comment]
That issue should be solved by now by upgrading yocto FW and switching to the USB connection.
