### ISSUE TITLE
00_install_yoctohub.sh not picking Yocto firmare version

### ISSUE THREAD

**Issue by vitbrando** [HYPERNETS/hypernets_tools#61]
in n00_install_yoctohub.sh
`if [ "$VERSION" -eq 0 ] ; then 
	output=$(wget https://www.yoctopuce.com/FR/common/getLastFirmwareLink.php -O -)
	VERSION=$(echo $output | cut -d',' -f1 | cut -d':' -f2)
	echo "Last version found on www.yoctopuce.com : $VERSION"
`

not working as  https://www.yoctopuce.com/FR/common/getLastFirmwareLink.php returns {} and not the version number!

from https://www.yoctopuce.com/EN/virtualhub.php release is  52382

so I did run the script successfully by calling  00_install_yoctohub.sh -n 52382

**Comment by corizzi** [comment]
Thanks @vitbrando ,  I add fd61c5027674d95abaf4b36d656d4bb8db57178d the correct installation procedure for debian (manually installation else).
