### ISSUE TITLE
python 3.9

### ISSUE THREAD

**Issue by saberioon** [HYPERNETS/hypernets_tools#7]
Unintentionally I have upgraded Manjaro, which lead to the upgrade of Python to version 3.9.1. Afterward, hypernets_tools is not working. Besides downgrading to version 3.8, any other solution available to fix it?

**Comment by corizzi** [comment]
It actually comes from libhypstar and its libboost dependence (compiled for python3.8). Happily, the new version of libhypstar won't use it (see https://github.com/HYPERNETS/libhypstar). So, I'll create a dedicated branch asap. In the meantime, you could try to re-run the 02_install_boost.sh script.

**Comment by saberioon** [comment]
Before I downgrade python to 3.8.5, I re-run the 02_install_boost.sh, but still, it had the issue with serial. I reinstall serial using pip but couldn't find Serial from serial.

**Comment by corizzi** [comment]
Did you used : 
`pip uninstall serial
pip install pyserial` ?

**Comment by saberioon** [comment]
After uninstalling serial and  installing pyserial, still encountering this error: 
`ImportError: cannot import name 'Serial' from 'serial' (unknown location)`

**Comment by corizzi** [comment]
`pip --version` ?

**Comment by saberioon** [comment]
pip 21.0

**Comment by corizzi** [comment]
What about `pip show pyserial` please?

**Comment by saberioon** [comment]
Name: pyserial
Version: 3.4
Summary: Python Serial Port Extension
Home-page: https://github.com/pyserial/pyserial
Author: Chris Liechti
Author-email: cliechti@gmx.net
License: BSD
Location: /home/gfz/.local/lib/python3.8/site-packages
Requires:
Required-by: pyftdi

**Comment by corizzi** [comment]
Seems good, are you sure that python command binds to python3.8 ?
`python -V`

**Comment by saberioon** [comment]
It seems python commands binds to python3.8, but to be sure I run `ln -sf /usr/bin/python3.8  /usr/bin/python3`, but it couldn't find serial

**Comment by saberioon** [comment]
> It seems python commands binds to python3.8, but to be sure I ran `ln -sf /usr/bin/python3.8 /usr/bin/python3`, but still it couldn't find serial
> 
> Python 3.8.5

I ran `pip uninstall serial` and `pip install pyserial` again, afterward, it works again! I didn't understand why this happen!
