### ISSUE TITLE
How to setup network ?

### ISSUE THREAD

**Issue by saberioon** [HYPERNETS/hypernets_tools#8]
Hi @corizzi , 

How to connect to the server for transmitting data automatically? I understand that the config file has the address and name of the folder for storing data but what about the password? Also How to force to upload data? Probably you write it somewhere but I couldn't find it. Your advice is appreciated

**Comment by javierconcha** [comment]
I also wonder about this. I remember from last week meeting that NPL or RBINS have to give us an account on the server. Is this related to that @clemgoyens?

**Comment by clemgoyens** [comment]
Hi Javier, Hi Mehdi,

Yes indeed, NPL will provide GFZ an account on the NPL server and Alex should give you the instructions on how to transfer the data automatically from the rugged PC to the server (I have some notes on how to do it but these are incomplete). For the water sites I still need to check how I can manage the RBINS server (sorry it has been on my to-do list for so long now!!). I will make sure the RBINS server will be able to welcome data from the water sites in February! Once I have tested it I will make you an account Javier and let you know about how to implement it!!

**Comment by corizzi** [comment]
Hi all !

@saberioon : yes, you well understood about the configuration file. For the password step and automatic mode at boot time, you can try this : 

`sudo ./install/08_setup_server_communication.sh`

When it asks about ssh passphrase and file location, let it empty (just press _enter_)

**Comment by saberioon** [comment]
Still, I cannot push readings automatically to the server even after I set it up! 

Any advise?

**Comment by corizzi** [comment]
Hi @saberioon!

Can you : 
`cat /etc/systemd/system/hypernets-hello.service` please ?

**Comment by corizzi** [comment]
Hello @saberioon , 

Can you test the following please : 
`cd hypernets_tools/`
`rm -rf LOGS/`
`sudo ./install/08_setup_server_communication.sh`

**Comment by saberioon** [comment]
> sudo ./install/08_setup_server_communication.sh

I have this outputs:

-- Journal begins at Wed 2020-10-07 14:12:00 CEST. --
Feb 03 01:57:27 gfz-pc1 hello_server.sh[901]: /home/gfz/Downloads/hypernets_tools/comm_server/hello_server.sh: line 35: LOGS/hypernets-sequence.log: Permission denied
Feb 03 01:57:27 gfz-pc1 systemd[1]: hypernets-hello.service: Main process exited, code=exited, status=1/FAILURE
Feb 03 01:57:27 gfz-pc1 systemd[1]: hypernets-hello.service: Failed with result 'exit-code'.
Feb 03 09:45:45 gfz-pc1 systemd[1]: Started Hypernets Sync Config Server and Send Data.
Feb 03 09:45:46 gfz-pc1 hello_server.sh[2602]: Sleep 30 sec
Feb 03 09:46:16 gfz-pc1 hello_server.sh[2610]: /home/gfz/Downloads/hypernets_tools/comm_server/hello_server.sh: line 35: LOGS/hypernets-sequence.log: Permission denied
Feb 03 09:46:16 gfz-pc1 systemd[1]: hypernets-hello.service: Main process exited, code=exited, status=1/FAILURE
Feb 03 09:46:16 gfz-pc1 systemd[1]: hypernets-hello.service: Failed with result 'exit-code'.
Feb 03 09:47:26 gfz-pc1 systemd[1]: Started Hypernets Sync Config Server and Send Data.
Feb 03 09:47:26 gfz-pc1 hello_server.sh[2708]: Sleep 30 sec
Feb 03 09:47:57 gfz-pc1 hello_server.sh[2708]: Sync files : gfz@139.143.5.63 :~/config_hypernets.ini.gfz
Feb 03 09:47:57 gfz-pc1 hello_server.sh[2708]:         <->  config_hypernets.ini
Feb 03 09:47:57 gfz-pc1 hello_server.sh[2708]: Sync from remote to local
Feb 03 09:47:57 gfz-pc1 hello_server.sh[2724]: ssh: Could not resolve hostname 139.143.5.63 : Name or service not known
Feb 03 09:47:57 gfz-pc1 hello_server.sh[2723]: rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
Feb 03 09:47:57 gfz-pc1 hello_server.sh[2723]: rsync error: unexplained error (code 255) at io.c(228) [Receiver=v3.2.3]
Feb 03 09:47:57 gfz-pc1 systemd[1]: hypernets-hello.service: Main process exited, code=exited, status=255/EXCEPTION
Feb 03 09:47:57 gfz-pc1 systemd[1]: hypernets-hello.service: Failed with result 'exit-code'.

**Comment by corizzi** [comment]
I guess there is a trailing space in your config file after the IP address ?

**Comment by corizzi** [comment]
should be fixed now, thanks for the feedback

**Comment by saberioon** [comment]
@corizzi 
first I manually remove space after the IP and it successfully synced. 

after your fix, I have tested it again and it successfully synced 👍🏼 
Feb 03 11:53:48 gfz-pc1 hello_server.sh[5516]: Sleep 30 sec
Feb 03 11:54:19 gfz-pc1 hello_server.sh[5516]: Sync files : gfz@139.143.5.63:~/config_hypernets.ini.gfz
Feb 03 11:54:19 gfz-pc1 hello_server.sh[5516]:         <->  config_hypernets.ini
Feb 03 11:54:20 gfz-pc1 hello_server.sh[5516]: Files are synchronized.
Feb 03 11:54:23 gfz-pc1 systemd[1]: hypernets-hello.service: Succeeded.

**Comment by saberioon** [comment]
Hi @corizzi , 

Somehow the communication between system and server interrupted and I cannot make the connection again!
this is the message in hello.log : 

-- Boot 8880823bd45646b4883b740dc100b1f5 --
Feb 24 17:39:07 gfz-pc1 systemd[1]: Started Hypernets Sync Config Server and Send Data.
Feb 24 17:39:07 gfz-pc1 hello_server.sh[742]: Sleep 30 sec
Feb 24 17:39:39 gfz-pc1 systemd[1]: hypernets-hello.service: Main process exited, code=exited, status=255/EXCEPTION
Feb 24 17:39:39 gfz-pc1 systemd[1]: hypernets-hello.service: Failed with result 'exit-code'.


Any advice?

**Comment by saberioon** [comment]
status of systemctl for hello service is show failing system: 
 
● hypernets-hello.service - Hypernets Sync Config Server and Send Data
     Loaded: loaded (/etc/systemd/system/hypernets-hello.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Mon 2021-03-01 16:06:32 CET; 1min 43s ago
    Process: 1034 ExecStart=/home/gfz/Downloads/hypernets_tools/comm_server/hello_server.sh (code=exited, status=255/EXCEPTION)
   Main PID: 1034 (code=exited, status=255/EXCEPTION)

Mär 01 16:06:02 gfz-pc1 systemd[1]: Started Hypernets Sync Config Server and Send Data.
Mär 01 16:06:02 gfz-pc1 hello_server.sh[1034]: Sleep 30 sec
Mär 01 16:06:32 gfz-pc1 systemd[1]: hypernets-hello.service: Main process exited, code=exited, status=255/EXCEPTION
Mär 01 16:06:32 gfz-pc1 systemd[1]: hypernets-hello.service: Failed with result 'exit-code'.

**Comment by clemgoyens** [comment]
Hi Mehdi,

I had the same error at Blankaart. I thought it was an issue with my account but apparently not. 
Can you check if you can sync

**Comment by saberioon** [comment]
> Hi Mehdi,
> 
> I had the same error at Blankaart. I thought it was an issue with my account but apparently not.
> Can you check if you can sync

@clemgoyens 
Nope, It is not syncing!

**Comment by clemgoyens** [comment]
Oops sorry Mehdi, I didn't realise my message left. I was looking for the command I used to sync (and which worked while I had the same error as yours). Ok maybe @corizzi  can help with it... 
Also can you connect from the rugged PC to the NPL server using your password and simple ssh command (ssh [account_name]@[npl server])?

**Comment by saberioon** [comment]
> Oops sorry Mehdi, I didn't realise my message left. I was looking for the command I used to sync (and which worked while I had the same error as yours). Ok maybe @corizzi can help with it...
> Also can you connect from the rugged PC to the NPL server using your password and simple ssh command (ssh [account_name]@[npl server])?

Yes, I can connect , it seems authorized keys is active, but still is not syncing !!
