### ISSUE TITLE
Rebooting & FAILURE Exit-code

### ISSUE THREAD

**Issue by adogliotti** [HYPERNETS/hypernets_tools#9]
@corizzi  

Last Wed we performed several test and we found the following issues and tired to guess the reason why. 
Note: Just to inform, we are using another GPS outside the window so we now have date/time and position all the time.

- Yocto rebooting 
It seems that if it does not find internet connection in the first minute (?), it sends the SOS signal and reboots until internet connection is found. When the cable is connected there is no problem, but using 4G Sim card, connection is less stable or takes a bit longer to connect so it reboots until it finds the connection (last day it took 3 reboots to connect). Is there a way to set this "searching for internet" time a bit longer so it gives time for the PC to get a signal?

- Last week we made two complete series, one OK and one exiting with a failure (no error mentioned in the log). Both did the 17 lines of the sequence and had the recorded files correctly in  the corresponding SEQ directories. The only difference was the PC KEEP ON/OFF option.  Given that sequence is correctly saved, could it be possible that this failure in exit-code is not really an error?
<pre>
-----------------------------------------------------------
ene 27 13:27:05 iafe1-pc run_service.sh[1571]: --> final pan : 349.9 ; final tilt : 0.18
ene 27 13:27:05 iafe1-pc run_service.sh[1571]: --> [Mode : non | Action : non | IT 0 ms] x 0 | total time : 0 ms]
ene 27 13:27:07 iafe1-pc run_service.sh[1174]: Option : Keep PC ON
ene 27 13:27:07 iafe1-pc systemd[1]: hypernets-sequence.service: Main process exited, code=exited, status=1/FAILURE
ene 27 13:27:07 iafe1-pc systemd[1]: hypernets-sequence.service: Failed with result 'exit-code'.
-------------------------------------------------
ene 27 15:13:29 iafe1-pc run_service.sh[1175]: --> final pan : 350.0 ; final tilt : 0.18
ene 27 15:13:29 iafe1-pc run_service.sh[1175]: --> [Mode : non | Action : non | IT 0 ms] x 0 | total time : 0 ms]
ene 27 15:13:32 iafe1-pc run_service.sh[934]: Option : Keep PC OFF
ene 27 15:13:32 iafe1-pc systemd[1]: hypernets-sequence.service: Succeeded.
</pre>
- We also had unexpected re-bootting of the system in the middle of a sequence without any clear reason.

Any news from Yocto or updates are very welcome so we can continue testing next Wednesday at the lab.
Thanks

Ana

**Comment by corizzi** [comment]
Hi @adogliotti, 

You are right about the error when _keep_pc = on_. This is not a real one. I just exit the script with the _general errors code : "exit-code"_  which causes _systemd_ to not power off.
About yoctopuce rebooting, sorry, we are still waiting answer from the developer team for the moment. I transmitted information from the GLPI ticket wrote by Joel) to them.

**Comment by jkuusk** [comment]
The rebooting issue has been solved by yocto FW upgrade.
